### ISSUE TITLE
[电脑问题?] 拖出残影

### ISSUE THREAD

**Issue by Dobby233Liu** [ZYFDroid/CaptureQrScanner#1]
![IMG_20190815_195921](https://user-images.githubusercontent.com/28653235/63094523-416cdb80-bf9b-11e9-9b9e-5c26d04eac7b.jpg)
[示例视频（不知道要上传到哪里。。。）](https://d2lstatics.ml/temp_videos/bandicam%202019-08-15%2019-52-03-097.mp4)

**Comment by ZYFDroid** [comment]
这是C#的特性
